repos:
 
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
   - id: check-toml
   - id: check-yaml
   - id: end-of-file-fixer
   - id: trailing-whitespace
  
  - repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
- id: isort
  name: Isort [_python_]
- repo: local
  hooks:
 - id: flake8
    name: Flake8
    description: This hook runs flake8 within this project's 
    poetry environment.
    entry: poetry run flake8
    language: system
    types: [_python__]
    require_serial: false
